- Resolved PDS-253: Updated Unix shell scripts and windows batch files to provide a more user friendly error message when JAVA_HOME is not set in the environment. - Fixed typo found in the Report Manager. Was referencing "RSUpdate" instead of "report-mgr" - Renamed shell script and windows batch file from "update-tool" to "RSUpdate" since the assembly.xml for the rs-update package references those names.
git-svn-id: https://starcell.jpl.nasa.gov/repo/2010/trunk@12864 45d5965c-88be-4637-9056-144873d6cd01

diff --git a/ingest/harvest/src/main/resources/bin/harvest b/ingest/harvest/src/main/resources/bin/harvest
--- a/ingest/harvest/src/main/resources/bin/harvest
+++ b/ingest/harvest/src/main/resources/bin/harvest
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright 2010-2011, by the California Institute of Technology.
+# Copyright 2010-2014, by the California Institute of Technology.
 # ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
 # Any commercial use must be negotiated with the Office of Technology Transfer
 # at the California Institute of Technology.
@@ -20,10 +20,10 @@
 
 # Expects the Harvest jar file to be in the ../lib directory.
 
-# Set the JAVA_HOME environment variable here in the script if it will 
-# not be defined in the environment.
-if [ -z ${JAVA_HOME} ] ; then
-  export JAVA_HOME=/path/to/java/home
+# Check if the JAVA_HOME environment variable is set.
+if [ -z "${JAVA_HOME}" ]; then
+   echo "The JAVA_HOME environment variable is not set." 1>&2
+   exit 1
 fi
 
 # Setup environment variables.
@@ -34,12 +34,12 @@ KEYSTORE=${PARENT_DIR}/keystore/tomcat_self_sign_keystore
 
 # Check for dependencies.
 if [ ! -f ${LIB_DIR}/harvest-*.jar ]; then
-    echo "Cannot find Harvest jar file in ${LIB_DIR}"
+    echo "Cannot find Harvest jar file in ${LIB_DIR}" 1>&2
     exit 1
 fi
 
 if [ ! -f ${KEYSTORE} ]; then
-    echo "Cannot find keystore file: ${KEYSTORE}"
+    echo "Cannot find keystore file: ${KEYSTORE}" 1>&2
     exit 1
 fi
 
@@ -48,5 +48,5 @@ HARVEST_JAR=`ls ${LIB_DIR}/harvest-*.jar`
 
 # Executes Harvest via the executable jar file
 # Arguments are passed in to the tool via '$@'
-${JAVA_HOME}/bin/java -Dpds.registry="http://localhost:8080/registry" -Dpds.security.keystore="${KEYSTORE}" -jar ${HARVEST_JAR} "$@"
+"${JAVA_HOME}"/bin/java -Dpds.registry="http://localhost:8080/registry" -Dpds.security.keystore="${KEYSTORE}" -jar ${HARVEST_JAR} "$@"
 
diff --git a/preparation/transform/src/main/bin/transform b/preparation/transform/src/main/bin/transform
--- a/preparation/transform/src/main/bin/transform
+++ b/preparation/transform/src/main/bin/transform
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright 2012, by the California Institute of Technology.
+# Copyright 2014, by the California Institute of Technology.
 # ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
 # Any commercial use must be negotiated with the Office of Technology Transfer
 # at the California Institute of Technology.
@@ -20,10 +20,10 @@
 
 # Expects the Transform Tool jar file to be in the ../lib directory.
 
-# Set the JAVA_HOME environment variable here in the script if it will
-# not be defined in the environment.
-if [ -z ${JAVA_HOME} ] ; then
-  export JAVA_HOME=/path/to/java/home
+# Check if the JAVA_HOME environment variable is set.
+if [ -z "${JAVA_HOME}" ]; then
+   echo "The JAVA_HOME environment variable is not set." 1>&2
+   exit 1
 fi
 
 # Setup environment variables.
@@ -33,7 +33,7 @@ LIB_DIR=${PARENT_DIR}/lib
 
 # Check for dependencies.
 if [ ! -f ${LIB_DIR}/transform-*.jar ]; then
-    echo "Cannot find Transform Tool jar file in ${LIB_DIR}"
+    echo "Cannot find Transform Tool jar file in ${LIB_DIR}" 1>&2
     exit 1
 fi
 
@@ -42,4 +42,4 @@ TRANSFORM_JAR=`ls ${LIB_DIR}/transform-*.jar`
 
 # Executes Transform Tool via the executable jar file
 # Arguments are passed in to the tool via '$@'
-${JAVA_HOME}/bin/java -Doverwrite.output=true -Dexternal.programs.home=${PARENT_DIR}/external-programs -jar ${TRANSFORM_JAR} "$@"
+"${JAVA_HOME}"/bin/java -Doverwrite.output=true -Dexternal.programs.home=${PARENT_DIR}/external-programs -jar ${TRANSFORM_JAR} "$@"
diff --git a/report/rs-update/src/main/resources/bin/RSUpdate b/report/rs-update/src/main/resources/bin/RSUpdate
--- a/report/rs-update/src/main/resources/bin/RSUpdate
+++ b/report/rs-update/src/main/resources/bin/RSUpdate
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright 2010-2011, by the California Institute of Technology.
+# Copyright 2010-2014, by the California Institute of Technology.
 # ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
 # Any commercial use must be negotiated with the Office of Technology Transfer
 # at the California Institute of Technology.
@@ -18,6 +18,12 @@
 # without the need to set the CLASSPATH or having to type in that long java
 # command (java gov.nasa.pds.report.update.RSUpdateLauncher ...)
 
+# Check if the JAVA_HOME environment variable is set.
+if [ -z "${JAVA_HOME}" ]; then
+   echo "The JAVA_HOME environment variable is not set." 1>&2
+   exit 1
+fi
+
 # Expects the Report Service Update jar file to be in the ../lib directory.
 
 SCRIPT_DIR=`dirname $0`
@@ -26,7 +32,7 @@ PARENT_DIR=`cd ${SCRIPT_DIR}/.. && pwd`
 LIB_DIR=${PARENT_DIR}/lib
 
 if [ ! -f ${LIB_DIR}/rs-update-*.jar ]; then
-    echo "Cannot find Report Service Update jar file in ${LIB_DIR}"
+    echo "Cannot find Report Service Update jar file in ${LIB_DIR}" 1>&2
     exit 1
 fi
 
@@ -35,5 +41,5 @@ RS_UPDATE_JAR=`ls ${LIB_DIR}/rs-update-*.jar`
 # Executes Report Service Update via the executable jar file
 # Arguments are passed in to the tool via '$@'
 
-java -jar ${RS_UPDATE_JAR} "$@"
+"${JAVA_HOME}"/bin/java -jar ${RS_UPDATE_JAR} "$@"
 
