PDS-132 : Includes updates to inline documentation for shell scripts. Updates to module documentation for more common errors and running more shell scripts.  New ops-index script.  New env-vars script.
git-svn-id: https://starcell.jpl.nasa.gov/repo/2010/trunk@11164 45d5965c-88be-4637-9056-144873d6cd01

diff --git a/search/search-core/src/main/resources/bin/initial-index b/search/search-core/src/main/resources/bin/initial-index
--- a/search/search-core/src/main/resources/bin/initial-index
+++ b/search/search-core/src/main/resources/bin/initial-index
@@ -1,36 +1,48 @@
-#! /bin/bash
+#!/bin/bash
 
-if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
+####################################################################
+#
+# initial-index
+#
+# Script used to generate an index using the search-core, and call
+# solr-post to post the data to the search-service
+#
+# $Id$
+#
+####################################################################
+
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+source ${DIR}/env-vars
+
+if [ $# -eq 3 ]; then
     SEARCH_HOME=${1}	
     SEARCH_SERVICE_URL=${2}
     REGISTRY_URL=${3}
-else
+elif [ "${SEARCH_HOME}" == "" ] || [ "${SEARCH_SERVICE_URL}" == "" ] || [ "${REGISTRY_URL}" == "" ]; then
     echo
-    echo "SEARCH_HOME, SEARCH_SERVICE_URL, and REGISTRY_URL must be specified via command-line"
-    echo "    ./initial-index <search-home> <search-service-url> <registry-url>"
+    echo "Usage: `basename $0` <search-home> <search-service-url> <registry-url>"
+    echo "    or specify variables in ${DIR}/env-vars"
     echo
-    exit 0
+    exit 1
 fi
 
 echo "-----------------------------------------------------"
-echo "----------------------WARNINGS------------------------"
 echo "-----------------------------------------------------"
-echo " RUN ON PDSBETA ONLY! "
-echo " - If on ops machine, kill script immediately."
-echo
 echo " - SEARCH_HOME = $SEARCH_HOME "
 echo " - SEARCH_SERVICE_URL = $SEARCH_SERVICE_URL "
 echo " - REGISTRY_URL = $REGISTRY_URL"
 echo "-----------------------------------------------------"
 echo "-----------------------------------------------------"
-echo "-----------------------------------------------------"
 
-# Need SEARCH_HOME to specify we are using the pds solr instance
-
+# Need SEARCH_HOME to specify we are using the PDS Solr instance
 echo $SEARCH_HOME
+
+# Check if search-core is in PATH
+hash search-core 2>/dev/null || { echo >&2 "search-core must be installed in PATH.  Aborting."; exit 1; }
 
 echo "-----Running search-core------"
 search-core -H $SEARCH_HOME -r $REGISTRY_URL
 echo "-----search-core Complete-----"
 
-./solr-post $SEARCH_HOME $SEARCH_SERVICE_URL
+solr-post
