Update docs and launch script and batch file to support the latest PDS security.
git-svn-id: https://starcell.jpl.nasa.gov/repo/2010/trunk@9288 45d5965c-88be-4637-9056-144873d6cd01

diff --git a/harvest/src/main/resources/bin/Harvest b/harvest/src/main/resources/bin/Harvest
--- a/harvest/src/main/resources/bin/Harvest
+++ b/harvest/src/main/resources/bin/Harvest
@@ -24,9 +24,15 @@ SCRIPT_DIR=`dirname $0`
 PARENT_DIR=`cd ${SCRIPT_DIR}/.. && pwd`
 
 LIB_DIR=${PARENT_DIR}/lib
+KEYSTORE=${PARENT_DIR}/keystore/tomcat_self_sign_keystore
 
 if [ ! -f ${LIB_DIR}/harvest-*.jar ]; then
     echo "Cannot find Harvest jar file in ${LIB_DIR}"
+    exit 1
+fi
+
+if [ ! -f ${KEYSTORE} ]; then
+    echo "Cannot find keystore file: ${KEYSTORE}"
     exit 1
 fi
 
@@ -35,5 +41,5 @@ HARVEST_JAR=`ls ${LIB_DIR}/harvest-*.jar`
 # Executes Harvest via the executable jar file
 # Arguments are passed in to the tool via '$@'
 
-java -Dpds.registry="http://localhost:8080/registry-service" -jar ${HARVEST_JAR} "$@"
+java -Dpds.registry="http://localhost:8080/registry-service" -Dpds.security.keystore="${KEYSTORE}" -jar ${HARVEST_JAR} "$@"
 
