Updated the assembly to include the default keystore directory and file. Restored the check for keystore in the launch scripts.
git-svn-id: https://starcell.jpl.nasa.gov/repo/2010/trunk@11384 45d5965c-88be-4637-9056-144873d6cd01

diff --git a/ingest/catalog/src/main/resources/bin/catalog b/ingest/catalog/src/main/resources/bin/catalog
--- a/ingest/catalog/src/main/resources/bin/catalog
+++ b/ingest/catalog/src/main/resources/bin/catalog
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright 2009-2012, by the California Institute of Technology.
+# Copyright 2009-2013, by the California Institute of Technology.
 # ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
 # Any commercial use must be negotiated with the Office of Technology Transfer
 # at the California Institute of Technology.
@@ -39,8 +39,8 @@ if [ ! -f ${LIB_DIR}/catalog-*.jar ]; then
 fi
 
 if [ ! -f ${KEYSTORE} ]; then
-    echo "WARNING: Cannot find keystore file: ${KEYSTORE}."
-    #exit 1
+    echo "Cannot find keystore file: ${KEYSTORE}."
+    exit 1
 fi
 
 # Finds the jar file in LIB_DIR and sets it to CATALOG_JAR.
