Updated namespace (urn:nasa:pds:context_pds3:*) with latest schema model.
git-svn-id: https://starcell.jpl.nasa.gov/repo/2010/trunk@11357 45d5965c-88be-4637-9056-144873d6cd01

diff --git a/ingest/catalog/src/main/resources/bin/catalog b/ingest/catalog/src/main/resources/bin/catalog
--- a/ingest/catalog/src/main/resources/bin/catalog
+++ b/ingest/catalog/src/main/resources/bin/catalog
@@ -39,8 +39,8 @@ if [ ! -f ${LIB_DIR}/catalog-*.jar ]; then
 fi
 
 if [ ! -f ${KEYSTORE} ]; then
-    echo "Cannot find keystore file: ${KEYSTORE}"
-    exit 1
+    echo "WARNING: Cannot find keystore file: ${KEYSTORE}."
+    #exit 1
 fi
 
 # Finds the jar file in LIB_DIR and sets it to CATALOG_JAR.
