Add pds.registry & pds.security.keystore properties.
git-svn-id: https://starcell.jpl.nasa.gov/repo/2010/trunk@10067 45d5965c-88be-4637-9056-144873d6cd01

diff --git a/ingest/catalog/src/main/resources/bin/catalog b/ingest/catalog/src/main/resources/bin/catalog
--- a/ingest/catalog/src/main/resources/bin/catalog
+++ b/ingest/catalog/src/main/resources/bin/catalog
@@ -30,10 +30,16 @@ fi
 SCRIPT_DIR=`dirname $0`
 PARENT_DIR=`cd ${SCRIPT_DIR}/.. && pwd`
 LIB_DIR=${PARENT_DIR}/lib
+KEYSTORE=${PARENT_DIR}/keystore/tomcat_self_sign_keystore
 
 # Check for dependencies.
 if [ ! -f ${LIB_DIR}/catalog-*.jar ]; then
     echo "Cannot find Catalog jar file in ${LIB_DIR}"
+    exit 1
+fi
+
+if [ ! -f ${KEYSTORE} ]; then
+    echo "Cannot find keystore file: ${KEYSTORE}"
     exit 1
 fi
 
@@ -42,4 +48,4 @@ CATALOG_JAR=`ls ${LIB_DIR}/catalog-*.jar`
 
 # Executes Catalog via the executable jar file
 # Arguments are passed in to the tool via '$@'
-${JAVA_HOME}/bin/java -jar ${CATALOG_JAR} "$@"
+${JAVA_HOME}/bin/java -Dpds.registry="http://localhost:8080/registry" -Dpds.security.keystore="${KEYSTORE}" -jar ${CATALOG_JAR} "$@"
